[mypy]
python_version = 3.11
mypy_path = src:stubs
explicit_package_bases = True
namespace_packages = True
files = src/app, src/service, src/scripts, tests

check_untyped_defs = True
disallow_incomplete_defs = True
no_implicit_optional = True
warn_unused_ignores = True
warn_redundant_casts = True
show_error_codes = True
pretty = True

# Stubs que no están (o que preferimos ignorar en CI)
[mypy-pandas.*]
ignore_missing_imports = True

[mypy-requests.*]
ignore_missing_imports = True

# Solo en tests: no exigir anotaciones en defs
[mypy-tests.*]
check_untyped_defs = False
disable_error_code = no-untyped-def
