replicaCount: 1

image:
  tag: "0.1.0-dev"

env:
  APP_ENV: "dev"
  LOG_LEVEL: "debug"

# Solo si tienes templates/ingress.yaml
ingress:
  enabled: true
  hosts:
    - "pharmaassistant.dev.tu-dominio.com"
