apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pharmaassistant.fullname" . }}-config
  labels:
    {{- include "pharmaassistant.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
