{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pharmaassistant.fullname" . }}
  labels:
    {{- include "pharmaassistant.labels" . | nindent 4 }}
  {{- if .Values.ingress.className }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "pharmaassistant.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
  {{- end }}
{{- end }}
