{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pharmaassistant.fullname" . }}-secrets
  labels:
    {{- include "pharmaassistant.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secrets.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
