apiVersion: v1
kind: Service
metadata:
  name: {{ include "pharmaassistant.fullname" . }}
  labels:
    {{- include "pharmaassistant.labels" . | nindent 6 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "pharmaassistant.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
