{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pharmaassistant.fullname" . }}
  labels:
    {{- include "pharmaassistant.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pharmaassistant.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: {{ .Values.serviceMonitor.portName }}
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
